### ISSUE TITLE
DiscordClient.UpdateStatus() not working

### ISSUE THREAD

**Issue by SulkyG** [NaamloosDT/DSharpPlus#53] opened 2017-05-04 10:37 UTC
Hi!

I'm getting a `System.NullReferenceException` when I'm using `_client.UpdateStatus("!help");`

Any idea why?

Thank you.

**Comment by Emzi0767** [comment] 2017-05-04 11:07
At a glance that's probably because your client is null. I would need to see more to tell.

**Comment by NaamloosDT** [comment] 2017-05-04 12:02
Hello there! Try setting your client status in the Ready event. Please tell me whether this changes anything :)

**Comment by NaamloosDT** [comment] 2017-05-09 20:10
I'm closing this issue because we haven't been able to reproduce the issue, also because you're not answering anymore.

**Closed by NaamloosDT** 2017-05-09 20:10 UTC
