### ISSUE TITLE
Double the members count is returned!

### ISSUE THREAD

**Issue by kef95** [NaamloosDT/DSharpPlus#93] opened 2017-07-16 00:42 UTC
In `GuildCreated` event, the `DiscordGuild.MemberCount` property returns double the amount of current members (including the bot). Going through the members one by one and checking the usernames returned half of them with empty or null usernames.

**Comment by Emzi0767** [comment] 2017-07-16 08:09
MemberCount returns the actual count. The members returned in GuildCreated event are only online members, so half is about right.

As for the usernames, you sure about that? I tested internally and only people who tested true for IsNullOrEmpty were people whose usernames are zero width spaces.

**Comment by kef95** [comment] 2017-07-16 21:17
You got me wrong. It returns "Double" not "Half" the number of users. There are 6 bots + me in a private server, and when the other bot joins it should be 8, not 16. So no, `MemberCount` definitely does not return the actual count.

**Comment by NaamloosDT** [comment] 2017-08-01 19:44
https://qt.vidyagam.es/1GEAG7Q.png
🤔

**Comment by NaamloosDT** [comment] 2017-08-01 19:47
I'm unable to reproduce this issue, could you give me some more info? or did emzi fix this?

**Comment by NaamloosDT** [comment] 2017-08-01 19:48
Leving this open for future reference

**Comment by NaamloosDT** [comment] 2017-08-01 20:52
Also added *Help Wanted* label, as we need help reproducing this issue and finding out what causes it.

**Comment by kef95** [comment] 2017-08-02 13:31
As far as I know, this only occurs in the `GuildCreated` event. Getting the guild members anywhere else works correctly!

**Comment by kef95** [comment] 2017-08-02 13:39
Still can be reproduced on latest version v2.5.4

**Comment by NaamloosDT** [comment] 2017-08-11 22:40
Able to reproduce now. Looking for a fix ASAP
https://qt.vidyagam.es/PQg74IW.png

**Comment by NaamloosDT** [comment] 2017-08-11 23:24
This should've been fixed in https://github.com/NaamloosDT/DSharpPlus/commit/d90d152dcb97818bd9f2ec890cad8a1842acbfb3 .

please reopen if it didn't fix for you.

**Closed by NaamloosDT** 2017-08-11 23:24 UTC
Labels: bug, core, help wanted
